### ISSUE TITLE
Implement GeometryType

### ISSUE THREAD

**Issue by peterstace** [peterstace/simplefeatures#103]
See https://postgis.net/docs/GeometryType.html

This function needs to be implemented both for `Geometry`, and for each concrete geometry type (e.g. `LineString`).

**Comment by peterstace** [comment]
Steps needed to finish this ticket:

- Add a `Type` method to each specific geometry (e.g. `LineString`, `Polygon` etc). It's return type should be `string`.
- Add a `Type` method to the `Geometry` type. It's return type should be `string`, and call the `Type` method on the geometry that it holds.
- Add fuzz checks for the `Type` method, using `GeometryType` PostGIS method as the reference implementation.

**Comment by eliteGoblin** [comment]
I'm tempted to reuse geometryTag.String() for Geometry.Type(): they both share the map

```
var tagTypeMap = map[geometryTag]string{
	geometryCollectionTag: "GeometryCollection",
	emptySetTag:           "EmptySet",
	pointTag:              "Point",
	lineTag:               "Line",
	lineStringTag:         "LineString",
	polygonTag:            "Polygon",
	multiPointTag:         "MultiPoint",
	multiLineStringTag:    "MultiLineString",
	multiPolygonTag:       "MultiPolygon",
}
```

So concrete type does not need to implement Type method. 

My concerns is that may created some unexpected coupling between concrete type and tag, what's main purpose of this tag and type, how they are different? 

And do concrete types need to implement their own Type() method as required by the standard?

**Comment by peterstace** [comment]
> what's main purpose of this tag and type, how they are different?

The `geometryTag` is used in the `Geometry` type to keep track of the type of geometry (e.g. `Line`, `Point` etc) held within the `Geometry`. This is the 'tag' part of a [Tagged Union](https://en.wikipedia.org/wiki/Tagged_union).

On the other hand, the `Type` method is defined by the OGC Simple Features Access specification, and is more of a way for a user to get a friendly description of what type of geometry that they have.

> My concerns is that may created some unexpected coupling between concrete type and tag

I agree, I don't think that we want to couple the two concepts together, even though they are similar (and coupling them _would_ reduce the amount of code required).

> And do concrete types need to implement their own Type() method as required by the standard?

Yes, that's correct. So it's probably going to be simpler _not_ to use a map, and just hardcode the type string in the `Type` method of each concrete type. And then the `Type` method of the `Geometry` type can do a switch on the tag, and call each concrete geometry's `Type` method.

**Comment by eliteGoblin** [comment]
take linestring for example: 

```
postgres=# SELECT ST_GeometryType(ST_GeomFromEWKT('LINESTRING (30 10, 10 30, 40 40)'));
 st_geometrytype 
-----------------
 ST_LineString
```

```
postgres=# SELECT GeometryType(ST_GeomFromEWKT('LINESTRING (30 10, 10 30, 40 40)'));
 geometrytype 
--------------
 LINESTRING
```

With function without `ST_ ` prefix, we got type string all uppercase, do we want this? or use `ST_GeometryType`, and remove result's `st_` prefix. 

I feel `LineString` is better than uppercase type.

**Comment by eliteGoblin** [comment]
Another question, how should we handle type for empty set? 
Our empty set could stand for 3 different types, right? 
*  point
*  LineString
*  EmptyPolygon

And the comment in type_empty.go is bit of confusing to me : 
> // EmptySet is a 0-dimensional geometry that represents the empty pointset.

**Comment by peterstace** [comment]
> I feel LineString is better than uppercase type.

I agree. I think we should use the `ST_GeometryType` behaviour, but remove the `ST_` prefix.

> Our empty set could stand for 3 different types, right?

That's correct.

> We should return the underlying type? that should be the same as postgis handle it

Agreed. E.g. `NewEmptyPolygon().Type()` should return `"Polygon"`.

> And the comment in type_empty.go is bit of confusing to me :

Yes, the comment isn't as clear as it could be. It would be better if the comment was more like:

```
// EmptySet represents either an empty Point, an empty LineString, or an empty Polygon.
```
