### ISSUE TITLE
Better Line/Line intersection

### ISSUE THREAD

**Issue by peterstace** [peterstace/simplefeatures#16]
As part of the convex hull work, we now have an 'orientation' function, that finds the orrientation (ccw vs cw vs colinear) for a sequence of 3 points.

That could be used to give a simpler line to line intersection test, e.g. similar to the approach used [here](https://www.geeksforgeeks.org/check-if-two-given-line-segments-intersect/). The current approach to line/line intersection is fairly add hoc, and with lots of edge cases.

**Comment by Den3** [comment]
https://github.com/peterstace/simplefeatures/pull/32
