### ISSUE TITLE
LineString/LineString intersection

### ISSUE THREAD

**Issue by peterstace** [peterstace/simplefeatures#29]
It currently uses a pairwise comparison on each line segment within the two line strings. We should be able to use a sweep line algorithm instead.

**Comment by Den3** [comment]
Because this issue and #28 will use the same algorithm, it will be better to have one person dedicated to that algorithm, @DoctorLoki and I decide to have @DoctorLoki to do both issues :)

**Comment by peterstace** [comment]
Fixed by #81 and #82 .
