### ISSUE TITLE
Instruction to use GEOS

### ISSUE THREAD

**Issue by AlexandreBorowczyk** [peterstace/simplefeatures#599]
Hi, 
I'm relatively new to Golang and I'm having issues accessing the GOES packages. I'm using VScode on Ubuntu 22.04 and I'm unable to import geos.

I've followed the instruction [here](https://askubuntu.com/questions/1347477/how-to-install-geos-on-ubuntu-20-04) while choosing the latest geos

I've install simplefeature with 
`go get github.com/peterstace/simplefeatures/geos `
`go get github.com/peterstace/simplefeatures/geom `

then
`go mod tidy`

Yet it seems like I still can't import it. 

Any help would be helpful!

**Comment by peterstace** [comment]
> Yet it seems like I still can't import it.

A few questions:

- What happens when you try to import it?
- Are you getting a compile error?
- Are you able to show the line in `go.mod` that shows the simplefeatures import?

**Comment by AlexandreBorowczyk** [comment]
The line in the `go.mod` is the following:
`github.com/peterstace/simplefeatures v0.47.1`

When I try to import it, as soon as I save the file vscode removed the import. Maybe it's a vscode issue?

**Comment by AlexandreBorowczyk** [comment]
So I bypassed vscode and the code build and executes 
So it seem it's a vscode issue

**Comment by peterstace** [comment]
I don't use vscode and don't know much about how it works so I can't really offer any suggestions. Sorry!

**Comment by AlexandreBorowczyk** [comment]
If this can help anyone, I've manage to fixed the issue by building the code without vscode then `go mod tidy` this added what was required to the mod.sum and vscode start recognizing the package afterward
