### ISSUE TITLE
Redundant node produced when using UnionMany function

### ISSUE THREAD

**Issue by congluoAtGrab** [peterstace/simplefeatures#642]
When I want to union multiple geometry, even though those geometries can fit perfectly, the result of UnionMany will produce some nodes that don't exist in the original geometries. Can the result of UnionMany only contains the node in the original geometries?

**Comment by peterstace** [comment]
Hi @congluoAtGrab , this is a known problem with the current DCEL implementation, which is used for the UnionMany operation. I'm tracking this problem in an existing issue (https://github.com/peterstace/simplefeatures/issues/487), so I'll close this one as a duplicate. Thanks for reporting!
